name: Publish

on:
  release:
    types:
      - created

jobs:
  Publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root
          path: ${{ env.pythonLocation }}
      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry-core
          python -m pip install poetry
      - name: Configure Poetry
        run: python -m poetry config virtualenvs.create false
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m poetry install
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry config pypi-token.pypi $PYPI_TOKEN
          bash scripts/publish.sh
